version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: locations
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'

  app:
    build: ./app
    container_name: app
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: locations
      ES_HOST: elasticsearch
    ports:
      - '3000:3000'
    depends_on:
      - db
      - elasticsearch
